defaults:
  - data: cifar100
  - model: cifar_resnet
  - method: baseline
  - training: cifar100
  - output: default
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  job_logging:
    disabled: true
  hydra_logging:
    disabled: true
